*** Variables ***
&{CARRINHO}
...         CLICK_WOMEN=//a[@class='sf-with-ul' and text()='Women']
...         ACTION_TSHIRT=//li[@class='ajax_block_product col-xs-12 col-sm-6 col-md-4 first-in-line first-item-of-tablet-line first-item-of-mobile-line']
...         CLICK_ADDCART=//a[@title='Add to cart' and @data-id-product='1']
...         TEXT_SUCESS=//span[@class='title']
...         CLICK_CROSS=//span [@class='cross']
...         CLICK_CART=//a[@title='View my shopping cart']
...         CLICK_LIXEIRA=//i[@class='icon-trash']
...         TEXT_CART_EMPTY=//p[@class='alert alert-warning']